### ISSUE TITLE
Trello Power-Up not showing/working on cards or board

### ISSUE THREAD

**Issue by rgomm** [danniehansen/activity-timer#105]
Maybe this is an Atlassian/Trello-side issue, but for several days now the Power-Up is not showing up at all on board or on cards.

Any possibility of fixing this?? My work time is stored in there that I need to invoice soon! 

Thank you very much for your wonderful work on a much-appreciated tool!!

**Comment by rgomm** [comment]
This appears to be totally an issue with my own network. Sorry to bother!

**Comment by danniehansen** [comment]
Hi @rgomm,

Sorry for not reacting sooner on your issue. Was/are in the middle of moving appartment, so might explain why i hadn't noticed. Glad that you got it solved 👍
