### ISSUE TITLE
New feature - Activity timer - Data exporter - Sort rows by time spent on task

### ISSUE THREAD

**Issue by MatejSz** [danniehansen/activity-timer#116]
Hi @danniehansen 
We quite enjoy the newly developed feature of sorting by label. Thank you.

It would be very useful for us in Activity timer - Data exporter- to sort rows by spent time. ("Time (seconds)" or "Time (formatted)").

This feature would help us to see which activities were top time consumers.

Thank you very much

Have a lovely day

**Comment by danniehansen** [comment]
Hi @MatejSz,

This should be covered and released when https://github.com/danniehansen/activity-timer/issues/121 is closed. Closing this issue to have a single one to keep track on 👍 Appreciate the feedback.
