### ISSUE TITLE
Exports

### ISSUE THREAD

**Issue by ERwoodside** [danniehansen/activity-timer#121]
Dannie, 
Is it possible to add a sort by to each of the columns in the Estimates/Data Exporter?  Ideally by date/chronological or reverse?
Is there a way to add a color indicator to estimates that total time have been used?
Thanks for these considerations, as always.
Jodi

**Comment by danniehansen** [comment]
Hi @ERwoodside,

Both good ideas! I'm planning to work some time on Activity timer this weekend. I will consider adding both sortable columns on the exporter as well as highlighting the badge of the estimates when they exceed the threshold (if this was what you was thinking?)

**Comment by ERwoodside** [comment]
Yep! Thanks!

**Comment by danniehansen** [comment]
@ERwoodside The work is done and current doing testing. Expect it to land some time during Wednesday. I overhauled the entire UI, so there is quite some testing to be done.

**Comment by ERwoodside** [comment]
Will be ready to test when you are!

Jodi Woodside
Director of Development & Optimization | Elite Research, LLC
Project Manager | Divergent Web Solutions, LLC
9901 Valley Ranch Pkwy. E., Ste. 2035, Irving, TX 75063
Phone: 972-538-1374 | 1-800-806-5661 ext. 714
www.eliteresearch.com | www.divergentwebsolutions.com
Fax: 1-800-806-5661 | ***@***.***
LinkedIn: https://www.linkedin.com/in/jodiwoodside/

*Note*:  All e-mails and files transmitted from Elite Research, LLC may
contain PRIVILEGED or CONFIDENTIAL information and may be used only by the
intended recipient.  Any use - dissemination, distribution, forwarding,
printing or copying of e-mails or any files (including templates) is
strictly prohibited.

**Comment by danniehansen** [comment]
Hi @ERwoodside,

Will you be able to check latest release how that works for you?

https://github.com/danniehansen/activity-timer/releases/tag/2.7.0

Now all columns should be sortable. Make sure if you wish to sort by time spent to sort by the seconds column.

**Comment by ERwoodside** [comment]
Hi Dannie,

The largest issue we are having is that the export is BLANK (both Chrome
and Edge).   Is it possible to resolve this quickly?

Jodi Woodside
Director of Development & Optimization | Elite Research, LLC
Project Manager | Divergent Web Solutions, LLC
9901 Valley Ranch Pkwy. E., Ste. 2035, Irving, TX 75063
Phone: 972-538-1374 | 1-800-806-5661 ext. 714
www.eliteresearch.com | www.divergentwebsolutions.com
Fax: 1-800-806-5661 | ***@***.***
LinkedIn: https://www.linkedin.com/in/jodiwoodside/

*Note*:  All e-mails and files transmitted from Elite Research, LLC may
contain PRIVILEGED or CONFIDENTIAL information and may be used only by the
intended recipient.  Any use - dissemination, distribution, forwarding,
printing or copying of e-mails or any files (including templates) is
strictly prohibited.

**Comment by danniehansen** [comment]
Hi @ERwoodside,

This problem should now be resolved. If you reload your browser and try again, then it should work. If it doesn't, then please confirm that you're running version 2.7.1 and if not, then try and clear your cache before trying again.
