### ISSUE TITLE
Estimate fields no longer accept decimal points

### ISSUE THREAD

**Issue by joancardonasa** [danniehansen/activity-timer#129]
It seems after an update a week or two ago, estimate fields no longer accept decimal points. That means the minimum estimate is now 1 hour per task. 

It doesn't work with either . or , (which is commonly used in Europe).

**Comment by danniehansen** [comment]
Hi @joancardonasa,

Thanks for reporting. The issue should be resolved in https://github.com/danniehansen/activity-timer/releases/tag/2.7.2 and again allow for decimals to be used 👍
