### ISSUE TITLE
Trackers stopping after some minutes

### ISSUE THREAD

**Issue by robsonsobral** [danniehansen/activity-timer#134]
Hi!

For some weeks, the trackers have been stopping after some minutes. It's generally 1 minute, but I have seen it stopped after 2, 5 or even more minutes.

I don't know it's related to #98 .

**Comment by danniehansen** [comment]
Hi @robsonsobral,

I'm currently digging into the issue and debugging. Can you help me by clearing one question?

Do you have auto-stop feature enabled under "Settings" on the card? If yes, could it simply be this? It defaults to be on.

I haven't been able to provoke it with few timers running for an hour. But i will try to keep it going.

**Comment by robsonsobral** [comment]
Thank you, @danniehansen !

"Stop on move"? Yes, it was. I disabled it. However, even unmoved cards stops.

Does it make any difference that I have more people working on the same board, but not always on the same cards?

**Comment by danniehansen** [comment]
@robsonsobral ah, good :)

It doesn't make a difference no. Activity timer has no way of knowing if you or someone else moved the card. We do a lot of trickery involving APIs and webhooks. So even in case someone else moves it, then it will also trigger the stop-on-move action 👍

**Comment by danniehansen** [comment]
@robsonsobral Scratch my last comment if you got to receive it, read your message wrong.

It shouldn't make a difference if someone else is working on the board. Activity timer supports a large quantity of users working together.

I'm still checking on my end. But do you think it could be that users may have moved the card, and then moved it back again? You should be able to check this in the card history :)

**Comment by robsonsobral** [comment]
> But do you think it could be that users may have moved the card, and then moved it back again? You should be able to check this in the card history :)

No, it couldn't. It sometimes happened, then we started to create separated cards for each other. I don't know whether it matters or not, but we have hundreds of cards on boards.

Thank you so much!

**Comment by danniehansen** [comment]
@robsonsobral okay. I'll try to see what i can do to simulate this. I no longer have any active boards that i can view to see how things work with many individuals. I know that performance can be harsh on boards with hundreds of cards, but it shouldn't provoke this. I'll see what i can find 👍

**Comment by danniehansen** [comment]
@robsonsobral The cards that you're having trouble with, how many tracking's roughly would you say it has attached to it?

I'm wondering what can provoke this as time tracking only stops during the following actions:

1. Card move list, then it stops your trackings on it if your setting for that is enabled
2. You stop it manually on the button
3. You open 'Manage time', click the running timer under there and stop it (you can see others too)

The most obvious cause would be #1. Maybe just to check now with the setting disabled and see if you're experiencing it again?

**Comment by grapheine** [comment]
Hello, here is an example of a video recording of the same problem...

https://www.dropbox.com/scl/fi/t1dnprwjicbfzoeh5zn9h/Enregistrement-de-l-cran-2024-01-09-16.19.56.mov?rlkey=9zn01yfy8rls0pa6mpsnyv8xa&dl=0

**Comment by danniehansen** [comment]
@robsonsobral @grapheine could either of you try the new 2.4.3 version? You can confirm if you're on this version by opening the activity timer board button.

I found a way to reproduce the problem all the time and managed to fix it. It was related to auto-stop functionality causing it to automatically stop on the next tick.

**Comment by grapheine** [comment]
Thank you very much, we do have the latest version 2.7.3.
I haven't had time to check it out yet, but it seems to be working properly again.

**Comment by robsonsobral** [comment]
@danniehansen , thank you so much! We haven't seen any more bugs.

Thank you so much!
