### ISSUE TITLE
Mobile Freeze

### ISSUE THREAD

**Issue by ERwoodside** [danniehansen/activity-timer#144]
Hi Dannie,

In the past couple of weeks, when accessing timers in mobile, the desktop redirects to Trello App and the Power Up for the Activity timer is unavailable. 

Jodi

**Comment by danniehansen** [comment]
Hi @ERwoodside,

I'm not sure what the redirect is about. It's not something that Activity timer is doing.

Regarding Activity timer accessibility in the Trello App. This is currently not possible as there is no Powerup support for Trello's app.

Please let me know if i misunderstood anything

**Comment by ERwoodside** [comment]
Thanks Dannie, yes, on the mobile browser, when the button to begin the
timer is selected it's somehow redirecting to the app where time tracking
is not possible.  We are unable to use activity timer from a mobile browser
at this time.

Jodi Woodside
Director of Development & Optimization | Elite Research, LLC
Project Manager | Divergent Web Solutions, LLC
9901 Valley Ranch Pkwy. E., Ste. 2035, Irving, TX 75063
Phone: 972-538-1374 | 1-800-806-5661 ext. 714
www.eliteresearch.com | www.divergentwebsolutions.com
Fax: 1-800-806-5661 | ***@***.***
LinkedIn: https://www.linkedin.com/in/jodiwoodside/

*Note*:  All e-mails and files transmitted from Elite Research, LLC may
contain PRIVILEGED or CONFIDENTIAL information and may be used only by the
intended recipient.  Any use - dissemination, distribution, forwarding,
printing or copying of e-mails or any files (including templates) is
strictly prohibited.

**Comment by danniehansen** [comment]
@ERwoodside I've checked the live version of Activity timer on a host of different devices. In the Chrome browser when starting/stopping the timer it works perfectly. Can you please try to test this on different devices and also on a clean Trello board with no other powerup than Activity timer? Just to confirm there is no interference from anything else.

**Comment by ERwoodside** [comment]
Hi Dannie,

See attached.

Jodi Woodside
Director of Development & Optimization | Elite Research, LLC
Project Manager | Divergent Web Solutions, LLC
9901 Valley Ranch Pkwy. E., Ste. 2035, Irving, TX 75063
Phone: 972-538-1374 | 1-800-806-5661 ext. 714
www.eliteresearch.com | www.divergentwebsolutions.com
Fax: 1-800-806-5661 | ***@***.***
LinkedIn: https://www.linkedin.com/in/jodiwoodside/

*Note*:  All e-mails and files transmitted from Elite Research, LLC may
contain PRIVILEGED or CONFIDENTIAL information and may be used only by the
intended recipient.  Any use - dissemination, distribution, forwarding,
printing or copying of e-mails or any files (including templates) is
strictly prohibited.

**Comment by danniehansen** [comment]
Hi @ERwoodside,

I cannot see your attachment on Github. You need to go through the web interface to share it.

**Comment by ERwoodside** [comment]
Sent through gmail!

Jodi Woodside
Director of Development & Optimization | Elite Research, LLC
Project Manager | Divergent Web Solutions, LLC
9901 Valley Ranch Pkwy. E., Ste. 2035, Irving, TX 75063
Phone: 972-538-1374 | 1-800-806-5661 ext. 714
www.eliteresearch.com | www.divergentwebsolutions.com
Fax: 1-800-806-5661 | ***@***.***
LinkedIn: https://www.linkedin.com/in/jodiwoodside/

*Note*:  All e-mails and files transmitted from Elite Research, LLC may
contain PRIVILEGED or CONFIDENTIAL information and may be used only by the
intended recipient.  Any use - dissemination, distribution, forwarding,
printing or copying of e-mails or any files (including templates) is
strictly prohibited.

**Comment by danniehansen** [comment]
@ERwoodside I've checked the video but it does not appear that anything Activity timer is showed before you click the link who goes to that page. Looks to be a Trello problem with linking between cards. This you need to raise with Trello :+1:

**Comment by ERwoodside** [comment]
Hi Dannie, I anticipated that Trello with a linked card is opening the app
to open the card instead of the browser -- how do we get activity timer to
the app :)  Thanks for all you do.

Jodi Woodside
Director of Development & Optimization | Elite Research, LLC
Project Manager | Divergent Web Solutions, LLC
9901 Valley Ranch Pkwy. E., Ste. 2035, Irving, TX 75063
Phone: 972-538-1374 | 1-800-806-5661 ext. 714
www.eliteresearch.com | www.divergentwebsolutions.com
Fax: 1-800-806-5661 | ***@***.***
LinkedIn: https://www.linkedin.com/in/jodiwoodside/

*Note*:  All e-mails and files transmitted from Elite Research, LLC may
contain PRIVILEGED or CONFIDENTIAL information and may be used only by the
intended recipient.  Any use - dissemination, distribution, forwarding,
printing or copying of e-mails or any files (including templates) is
strictly prohibited.

**Comment by danniehansen** [comment]
@ERwoodside I would have anticipated as well. Might be worth reporting this to Trello.

Activity timer cannot come to the App since the App does not support powerups. So unfortunately this is not possible.

**Comment by ERwoodside** [comment]
Thanks Dannie for your quick reply - will report.

Jodi Woodside
Director of Development & Optimization | Elite Research, LLC
Project Manager | Divergent Web Solutions, LLC
9901 Valley Ranch Pkwy. E., Ste. 2035, Irving, TX 75063
Phone: 972-538-1374 | 1-800-806-5661 ext. 714
www.eliteresearch.com | www.divergentwebsolutions.com
Fax: 1-800-806-5661 | ***@***.***
LinkedIn: https://www.linkedin.com/in/jodiwoodside/

*Note*:  All e-mails and files transmitted from Elite Research, LLC may
contain PRIVILEGED or CONFIDENTIAL information and may be used only by the
intended recipient.  Any use - dissemination, distribution, forwarding,
printing or copying of e-mails or any files (including templates) is
strictly prohibited.
