### ISSUE TITLE
Manually edit tracked time

### ISSUE THREAD

**Issue by jknechtl** [danniehansen/activity-timer#28]
Hi, it would be lovely to be able to change / add / remove tracked time. In case where you forgot to stop / start time tracking button.

**Comment by jknechtl** [comment]
Or make it bit more user friendly (found it just now)

**Comment by danniehansen** [comment]
@jknechtl I've tried to cover this area in the readme of the powerup. Unfortunately Trello doesn't provide much better UI controls than what we go at the moment. I'll leave this issue open as a discussion board regarding this.

Do you have any suggestions as to how the "Manage time" section could be improved?

**Comment by natekwilson** [comment]
Something similar to how the Trello Plus extension manages manual time additions. Just give a small blank input box for a number of hours and have it assume that you just completed those hours at the present time. (this could be then edited by the existing 'manage time' section on the right). Does the extension have a mandated reality check for overlapping work windows?

https://4.bp.blogspot.com/-U-WrbAjMETs/VXvOX1DyjaI/AAAAAAAASHI/gyw22QmJbt8/s400/cardse.png

**Comment by danniehansen** [comment]
@natekwilson Sorry for the crazy late reply. Haven't noticed your comment. Just now implemented a way of manually adding time under 'Manage time'. When you have at least one tracking you can add additional trackings manually.

Unfortunately there is no checks for overlapping trackings. I'd be more than happy to look into this. Could you open a separate issue for this?

**Comment by TinaKaltoft** [comment]
Hi @danniehansen  - is it possible to add time manually, without having any tracking on the card? Or can it be made as possible?

**Comment by danniehansen** [comment]
Hi @TinaKaltoft - not possible at the moment but I'll implement it here within a week or two. Not sure why I made it an option only when at least 1 time track logged..

**Comment by danniehansen** [comment]
@TinaKaltoft Added in https://github.com/danniehansen/activity-timer/releases/tag/1.2.2
