### ISSUE TITLE
Automatically move card to list when time tracking starts

### ISSUE THREAD

**Issue by danniehansen** [danniehansen/activity-timer#4]
A requested feature as of lately. A setting allowing cards to be automatically moved to a specific list of your choice when you start tracking time. Very useful if you have a 'In progress' list for your cards.

**Comment by LexGear** [comment]
I second this. Everyone in my office who I've just gotten onto this power-up is asking for automatic start timer when moving card to list, or something similar to what is described above.

**Comment by danniehansen** [comment]
@LexGear Have an update on this. Until now I haven't been able to think of a way of archiving this. This have been due to limitations in the plugin system Trello made where i wont be able to know which user moved a card from A -> B. Without this knowledge i could not possibly start the timer for the correct person.

(Technical v )
However - I found that if i request access to the REST API I'm able to register a webhook that will notify a service of mine about any change on the cards for the board. This would allow me to recognize card moves. There is still 2 questions left to answer:

1. Will i know in the webhook who actually moved the card?
2. Billing. Moving logic onto a server & not handling everything client side brings costs. I need to either find a way to monetize this feature or pay it out of my own pocket.

1. I'm still researching this.
2. Debating with myself about this.

**Comment by danniehansen** [comment]
@LexGear I've released a beta feature that allows for this. There is no such thing in the Trello SDK that allows me to do this - so I've had to go through a lot of loop-holes to get it working.

You should (after clearing browser cache) be able to access new settings for enabling this feature under your power-up settings. Please note that this is not the 'Settings' card button shown when on a card - but the administrators 'Power-up' settings for Activity timer. Here you'll be able to enable the feature & choose which list should auto-start the timer.

Technical details:

When enabling it will request access to act on your behalf. This is so that we can register a webhook that will notify a service hosted by me whenever changes to the board occurs. Within this webhook I'm able to detect the action when a user moves a card from list A to list B. While there is no built-in functionality for communicating with the frontend or setting data that i can fetch in the frontend to start the timer - i still got it working. Worked in a Websocket that will be used by the webhook to communicate when to start a timer on the frontend.

There can be a slight delay on when it registers that it needs to start the timer. It should always do it - but i can take some seconds (1-10) to take into effect. Most cases it happens right away. This is due to me using the card badges to allow for starting the timer. Badges refresh every 2 second & allows me to have the context of the card for starting the timer.

-

Overall I'm very happy with the result. Let's see how it plays out in the wild :) Let me know if you have any feedback on this.

**Comment by LexGear** [comment]
Sorry for the late reply! Thank you so much for doing this. I'm going to
play around with it now. Just initial testing shows it is not triggering,
but let me play with it a bit more.

*Regards,*
*Luke Molnar*

**Comment by danniehansen** [comment]
@LexGear You might need to re-enable the feature. If you've used 'Activity timer history' then you've likely given a more restrictive access to the power-up than which is asked on the 'auto timer' setting. However - due to restrictions with the SDK available i cannot detect how much privilege a given access has. Disabling the auto-move and enabling it again might solve this - as disabling will revoke the access & you will then be prompted on fresh when you try and enable it again.
