### ISSUE TITLE
Manually added time is not visible in `Manage time` listing, neither in `Activity Timer History` (since 1.2.0)

### ISSUE THREAD

**Issue by jonez1** [danniehansen/activity-timer#46]
Hello Dannie.
I've noticed some new features, but i've found a bug when adding spent time to the task through `Add manually` link.
This manually added time is not visible in `Manage Time` at the task sidebar (see figure 1), neither in `Activity Timer History` (see figure 2).

Replication of the issue described on the figure one.
- [1] recorded some time through running timer
- [2] added 35mins manually
- [3] total time updated, bud the entry did not show up at `Manage Time`

To be more specific, i've found, that the most probable reason is the manually added time is not assigned to current user.

I've readded rights to the power-up, refreshed the Trello couple times, none of those steps had any positive effect.

![1-activity_timer-lost_time_entries](https://user-images.githubusercontent.com/33315573/122244229-01dbe700-cec5-11eb-9ac0-a50aabea88bd.png)

![2-activity_timer-history](https://user-images.githubusercontent.com/33315573/122244322-16b87a80-cec5-11eb-9e1b-0e3b45dda736.png)

**Comment by danniehansen** [comment]
Hi @jonez1 

First of all - really appreciate the descriptive issue, on point. You're absolutely right - looks like I've forgot to assign the member when manually adding time. I'll push a fix out here later tonight or tomorrow.

Once again. Appreciate it.

**Comment by danniehansen** [comment]
@jonez1 This is fixed in 1.2.1 - also made invisible time trackings or trackings for users not there anymore appear under "Manage time" / "Time spent".

Once again thanks for reporting.
