### ISSUE TITLE
Option to record activity description

### ISSUE THREAD

**Issue by beniza** [danniehansen/activity-timer#61]
### Feature Request
As a **user** 
I would like to **have an option to add a small description (preferably rich text) of the activity being logged**
So that **I'll be able to better analyze and stream my activities**

### Addl. Info.
Thanks for this excellent time tracker, especially that you're keeping this open source. 🙏. I believe having an option to add a small note (*preferably in rich text format*) can enhance the overall user experience and the usefulness of this **Power Up**. Kindly consider.

**Comment by danniehansen** [comment]
Hi @beniza,

Great suggestion. Actually had this one on my mind for some time as well. Unfortunately it comes with some limitations that could dramatically limit the usability of Activity timer. You see, Trello have limited the amount of data that a powerup can save on a card to 4KB. & if you use Activity timer to do a lot of tracking's in an individual card it quickly adds up.

If this should also feature notes on these tracking's - then it would hit the limit even faster.

For now I won't be able to implement this feature. But if enough subscribe to the pro version I would reconsider it. The reason why is that now we're relying on Trello to hold all of the data. If this was to become a reality i would have to work out my own backend that contain all of the time tracking's and then there have references for notes.

Let's keep the card open for now. And see what others think of it. Then if enough subscribe I'll reconsider it.

**Comment by beniza** [comment]
Thank you @danniehansen for your quick and detailed response. I didn't know about the 4KB limitation. Although it would have been nice to have this feature, I understand that it can introduce other usability issues. Thanks for considering to keep this option open.

**Comment by danniehansen** [comment]
Closing this issue for now due to the constraints that we work with wouldn't allow for this feature. Thank you for the original suggestion @beniza 👍

**Comment by beniza** [comment]
Hi @Danny Hansen

Thank you for considering my suggestion. To be honest with you, I have long
forgotten about this. Yea, if there's limitation in implementing this
feature, I agree with you on closing this.

Thank you again for considering my suggestion. Really appreciate it. All
the best with your project.

Regards
BeNiza
