### ISSUE TITLE
Sometimes activity timer record different time than what shows in webbrowser

### ISSUE THREAD

**Issue by MatejSz** [danniehansen/activity-timer#67]
We find out that sometimes activity-timer records different times than what shows in a web browser.
So recorded time on the end may be incorrect.

Please see attachment
https://user-images.githubusercontent.com/45109239/155297011-620e350a-9c1c-402c-98f9-ed51f230de36.mp4

Unfortunately, we still have not found out reproduction step to this bug.
It's just happened occasionally, most of the time it works fine.

Browser: Chrome
Version: Pro version of activity timer

**Comment by MatejSz** [comment]
hi @danniehansen 
Thank you for your reply.

We tried the timer again on the previously bugged Trello task, but it works fine this time.
You wrote "The above error happens when your card is cluttered with too many tracking's. "
I don't think we had this error as you can see in the video in the second 0:13.
There you see totally time is only 3 minutes which should not be too many trackings. 

But on the other hand sometimes during stand-up, we use a timer 4-5 people at the same time on the same task.

**Comment by danniehansen** [comment]
Hi @MatejSz,

Ah. I see that at 0:13 - then yes, this shouldn't be the case. I will look into it to see if i can locate it. Thank you with the detail that you might be working many people on the same card at the same time, that could be resolved. Will keep this in mind when debugging.

Thank you.

**Comment by danniehansen** [comment]
@MatejSz 

I've done some extensive testing on 2 users tracking on the same the same card & have been unable to provoke that which you're describing here. However, i did notice that if two users are tracking on the same card & one of them move it. Then it only saves the tracking for one of the users and not both.

To further investigate this. Could you help clarify a few things?

1. Which settings are you using under Powerup -> Settings (general powerup settings)?
2. Which settings are you using under Card -> Settings (private member settings)?
3. Are multiple users tracking on the same card when this is happening?
4. Are there any chance another user which might be tracking on the same card, moves the card as you click it?


Either way i will be fixing the movement issue in next patch. But it would be nice to get an indication if this might be it.

**Comment by danniehansen** [comment]
I'll close this item due to inactivity. Please fell free to re-open if there is any update.
