### ISSUE TITLE
Manage time - missing total time for each user.

### ISSUE THREAD

**Issue by MatejSz** [danniehansen/activity-timer#75]
It would be nice if we could see the total time for each user.
Now we can see only a list of separate times see the screen.
![Manage time - missing total time for each user](https://user-images.githubusercontent.com/45109239/180223616-0400f825-05c3-438d-9f9d-ac970cfc5f42.png)

Trello - -> choose card -> manage time button

**Comment by danniehansen** [comment]
Hi @MatejSz,

This is actually possible through the 'Time spent' card button. However, we already have the data available at this view & could make total sense just to include the time in the line where the users name are. I'll include this in my release next week. Appreciate the feature request :)

**Comment by danniehansen** [comment]
Hi @MatejSz,

This is now implemented and ready to get released with version 2.2. Also made it include running tracking's in the 'Time spent' window. Will notify here when it is out.

**Comment by MatejSz** [comment]
Super. Thx @danniehansen

**Comment by danniehansen** [comment]
@MatejSz Sorry for the delay. It's now been released with https://github.com/danniehansen/activity-timer/releases/tag/2.2.0

**Comment by MatejSz** [comment]
Super @danniehansen .
It works lovely now.
