### ISSUE TITLE
Manage time - No information who is working on the card, until stoping the timer

### ISSUE THREAD

**Issue by MatejSz** [danniehansen/activity-timer#76]
It would be nice if we could see who is working on a task, now until the user stops the timer there is no way to know who is working on the task.
![Manage time - until timer is stop there is no way to know who is working on task](https://user-images.githubusercontent.com/45109239/180226409-e8e1c0fe-05fe-4a48-8f2d-eda811d5abaa.png)

**Comment by MatejSz** [comment]
This function would be also beneficial in a case when somebody forgets to stop the timer.

**Comment by danniehansen** [comment]
Hi @MatejSz,

Great suggestion. I'll look into this next week and implement this. Sounds like a great addition. I'll reference the merge request in this issue and ask for feedback from you (showing screenshots) before I'll release it.

**Comment by danniehansen** [comment]
Hi @MatejSz,

The functionality is now ready for 2.2

See the following screenshot: https://i.imgur.com/6ZnZOOk.png

Also added the ability to click on any running tracking's and have the ability to stop them: https://i.imgur.com/vZSBnuH.png

**Comment by MatejSz** [comment]
Super @danniehansen .
Looking forward.

**Comment by danniehansen** [comment]
@MatejSz Sorry for the delay. It's now been released with https://github.com/danniehansen/activity-timer/releases/tag/2.2.0

**Comment by MatejSz** [comment]
Thank you @danniehansen 
Test OK
