### ISSUE TITLE
Show Estimate time in trello attachment card

### ISSUE THREAD

**Issue by MatejSz** [danniehansen/activity-timer#77]
It would be nice to have an Estimate time in the Trello attachment card.
So the card would look the same as on the Trello board
![Estimate in Trello attachment card](https://user-images.githubusercontent.com/45109239/180229275-e35887ae-a049-4301-9e20-5cf660cb8fc1.png)

It would be also nice to see on this card already recorded time.

Thank you very much Dannie.I hoped I have not overwhelmed you with new cards ;)

**Comment by MatejSz** [comment]
It would be also nice to see on this card already recorded time.

Thank you very much Daniel.

**Comment by danniehansen** [comment]
Hi @MatejSz,

Thank you for the feature request. I hadn't thought of this just yet, great suggestion.

Initially when looking into it, it does not appear that through a powerup that you can modify this part. I'll leave the card open & dig further here next week. But at it's current state it doesn't look to be feasible with the current Trello API.

**Comment by danniehansen** [comment]
Putting it in on version 2.2 for discovery on if it's possible & include it if it is.

**Comment by danniehansen** [comment]
Hi @MatejSz,

Further research doesn't show any way to hook into this view and allow powerups to manipulate it. So unfortunately we're unable to introduce such functionality. Would have been a great addition though. Appreciate the feature request.

**Comment by MatejSz** [comment]
Ok understand.
