### ISSUE TITLE
Copied tasks inherits time records from original task

### ISSUE THREAD

**Issue by jonez1** [danniehansen/activity-timer#87]
Hello Dannie,
i'd like to report strange behavior i've noticed lately.

I have made a copy of one task where was some time measured, and the copy retained the recorded values from the original task.
I thought the time records were also duplicated, so i've deleted it ( `Manage Time > Clear` ), but it deleted the records at the original task too, which leads me to conclusion, that it inherited just the pointers from original task.
By my opinion, every copy of the original task should have its time records cleaned.

Few pictures to document the issue.
![original_task](https://user-images.githubusercontent.com/33315573/203119846-0f6db16d-00bd-4e1d-b04c-b6964fac45c9.png)
![copy_of_the_task](https://user-images.githubusercontent.com/33315573/203119866-ee7e9d88-b2d5-42b1-9225-7a2c9ae356e0.png)

**Comment by danniehansen** [comment]
Hi @jonez1,

Sorry for the delay in my reply. Have been a busy few weeks.

I'll be looking into this issue this weekend 👍 I'm wondering how this can be or what i could do about it. The copy functionality is entirely Trello managed. But i will investigate and provide my findings.

**Comment by danniehansen** [comment]
Closing issue for now. Please just reply to re-open if there are any news @jonez1
